sudo: false
language: node_js
node_js:
    - "12"
    - "10"
cache:
    npm: true
install:
    - npm audit
    - npm install
script:
    - npm run build
    - npm run lint
    - npm run test
after_success:
    - npm run coveralls
